### PR TITLE
chore(dependencies): update dependencies and integrate Yarn

### PR DESCRIPTION
**Pull request by yhuard**

### CODE REVIEW

**Comment by kalinchernev** [comment]
Running the build, things seemed to be ok.
During the up, several errors occurred. This is a snipped from the end of the script:

```
cope-couchdb | [notice] 2017-01-10T16:00:37.598661Z nonode@nohost <0.3308.0> b841951217 couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes 404 ok 1
cope-couchdb | [notice] 2017-01-10T16:00:37.613757Z nonode@nohost <0.3309.0> 452656f98e couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes 404 ok 2
cope-couchdb | [notice] 2017-01-10T16:00:37.626347Z nonode@nohost <0.3310.0> 4046036c57 couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes 404 ok 1
cope-couchdb | [notice] 2017-01-10T16:00:37.640205Z nonode@nohost <0.3311.0> 1fbb569447 couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes 404 ok 1
cope-changes | 2017/01/10 16:00:41 Timeout after 1m0s waiting on dependencies to become available: [http://couchdb:5984/ilayer/_design/facade/_rewrite/beta/changes]
cope-couchdb | [notice] 2017-01-10T16:00:41.393865Z nonode@nohost <0.3344.0> 34e7ebdb7a couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes 404 ok 6
cope-changes | 
cope-changes | > integration-layer-backend-changes@0.1.0 start /usr/src/app
cope-changes | > node index.js
cope-changes | 
cope-couchdb | [notice] 2017-01-10T16:00:42.777148Z nonode@nohost <0.3345.0> 587ec9419e couchdb:5984 172.19.0.3 undefined GET /ilayer/_design/facade/_rewrite/beta/changes/?heartbeat=30000&feed=continuous&style=main_only&since=0 404 ok 1
cope-changes | events.js:160
cope-changes |       throw er; // Unhandled 'error' event
cope-changes |       ^
cope-changes | 
cope-changes | Error: Received a 404 from couch
cope-changes |     at ChangesStream.handleOnResponse [as _onResponse] (/usr/src/app/changes-stream.js:183:11)
cope-changes |     at Object.onceWrapper (events.js:290:19)
cope-changes |     at emitOne (events.js:101:20)
cope-changes |     at ClientRequest.emit (events.js:188:7)
cope-changes |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
cope-changes |     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
cope-changes |     at Socket.socketOnData (_http_client.js:362:20)
cope-changes |     at emitOne (events.js:96:13)
cope-changes |     at Socket.emit (events.js:188:7)
cope-changes |     at readableAddChunk (_stream_readable.js:176:18)
cope-changes | 
cope-changes | npm ERR! Linux 4.4.0-57-generic
cope-changes | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
cope-changes | npm ERR! node v7.4.0
cope-changes | npm ERR! npm  v4.0.5
cope-changes | npm ERR! code ELIFECYCLE
cope-changes | npm ERR! integration-layer-backend-changes@0.1.0 start: `node index.js`
cope-changes | npm ERR! Exit status 1
cope-changes | npm ERR! 
cope-changes | npm ERR! Failed at the integration-layer-backend-changes@0.1.0 start script 'node index.js'.
cope-changes | npm ERR! Make sure you have the latest version of node.js and npm installed.
cope-changes | npm ERR! If you do, this is most likely a problem with the integration-layer-backend-changes package,
cope-changes | npm ERR! not with npm itself.
cope-changes | npm ERR! Tell the author that this fails on your system:
cope-changes | npm ERR!     node index.js
cope-changes | npm ERR! You can get information on how to open an issue for this project with:
cope-changes | npm ERR!     npm bugs integration-layer-backend-changes
cope-changes | npm ERR! Or if that isn't available, you can get their info via:
cope-changes | npm ERR!     npm owner ls integration-layer-backend-changes
cope-changes | npm ERR! There is likely additional logging output above.
cope-changes | 
cope-changes | npm ERR! Please include the following file with any support request:
cope-changes | npm ERR!     /usr/src/app/npm-debug.log
cope-changes exited with code 0
```

The undefined message was repeated many more times before this.

**Comment by yhuard** [comment]
It failed because it was too slow to boot: `cope-changes | 2017/01/10 16:00:41 Timeout after 1m0s waiting on dependencies to become available`. It's an issue I try to avoid by using https://github.com/jwilder/dockerize, but sometimes it's not enough. Try it again or increase the timeout value in `./docker/changes/docker-setup.sh`.

Note to myself: handle errors.

**Comment by yhuard** [comment]
Or even better: [launch the 3 docker instances separately](https://github.com/ec-europa/cope-api/blob/master/docs/docker.md#step-by-step), one after the other.

**Comment by yhuard** [comment]
In the latest node docker images, yarn is already integrated 🎉

**Review by kalinchernev — APPROVED** [review]
Works well now! :)

**Pull request merged**
